Add support for storage and overhead price
eosnetworkfoundation/eos-evm-contract pull request #750
Opened 2024-07-08 23:59 UTC by elmato

2024-07-31 00:53 UTC, yarkinwho requested changes

2024-07-31 00:53 UTC, yarkinwho commented on tests/basic_evm_tester.hpp
> +struct evmtx_v1 : evmtx_base {
Shall we still keep the base price in evmtx_v3 so that it would be possible to implement the option to still use old model with high eos evm version?

2024-08-05 06:08 UTC, yarkinwho approved these changes
Seems fine, but two issue:
1 will gas_price and gas_prices cause confusion?
2 when we upgrade from v2 to v3, we stop using gas_price_queue. seems there missing some mechanism to clear the value stored (if any) n that table afterwards?

2024-08-05 21:57 UTC, elmato commented
> Seems fine, but two issue: 1 will gas_price and gas_prices cause confusion? 2 when we upgrade from v2 to v3, we stop using gas_price_queue. seems there missing some mechanism to clear the value stored (if any) n that table afterwards?

1) They are similar but the types/functions/actions are very different. We couldn't find a better name for the pair storage_price/overhead_price :/.

2) ~We don't allow the change from v2 to v3 if there are pending prices in the queue~. Seems that check is missing in the current PR. Will update it

2024-08-08 01:47 UTC, merged